### ISSUE TITLE
Please update packages to latest version

### ISSUE THREAD

**Issue by mashegoindustries** [wilburt/rave_flutter#40]
Package not working with my project, causing build errors because of an outdated package

../../../../.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.17.4/lib/src/picture_stream.dart:88:26: Error: Type 'DiagnosticableMixin' not found.
class PictureStream with DiagnosticableMixin {

**Comment by brad007** [comment]
as well as get it

**Comment by WianSnyman** [comment]
I have also run into this issue. The package dependency flutter_svg requires an update to 0.18.0.

**Comment by fried19** [comment]
I have the same error

**Comment by WianSnyman** [comment]
For now I had to downgrade flutter to 1.16.3.
Navigate to the flutter install directory and do "git checkout 1.16.3" (previous stable flutter release) , then flutter doctor.
Remember to do a flutter clean afterwards. For iOS you might need to delete your Pod files as well because
of the downgrade (similar steps for an upgrade).

**Comment by fried19** [comment]
Ok thank you @WiamSnyman.I will try it and let you know

**Comment by fried19** [comment]
It means that this package does no more works with flutter 1.21.0 ? @WianSnyman

**Comment by wilburx9** [comment]
Sorry for this guys, I have been super busy. I will work on updating the packages and squashing a couple of bugs in the coming week.

For the meantime, if downgrading Flutter is too much of a hassle, you can try overriding the dependencies; hopefully, that won't break anything.

**Comment by WianSnyman** [comment]
> It means that this package does no more works with flutter 1.21.0 ? @WianSnyman

For the package flutter_svg 0.17.4  it seems so. Hence the upgrade from 0.17.4 to 0.18.0 is required for the latest flutter version.

@wilburt We appreciate your time and effort, thanks a mil!

**Comment by fried19** [comment]
Yes @wilburt I think overriding the flutter_svg is better and it works for me.Thank you for your attention and I am waiting for the package update.Thank you also @WianSnyman

**Comment by wilburx9** [comment]
Please, update to to `0.0.9-alpha+2`.

**Comment by austyking** [comment]
> Please, update to to `0.0.9-alpha+2`.

Thanks @wilburt  but `0.0.9-alpha+2` uses `flutter_svg 0.18.1` which seems not to work with `Flutter 1.22.2`. Perhaps you will have to update package again

**Comment by wilburx9** [comment]
@austyking, Please, what version of Flutter are you using? `flutter packages get` appears to be running as at version 1.22.3.

**Comment by austyking** [comment]
@wilburt Sorry for the delay in response...I am using **Flutter version 1.22.2**. This is the message I get while installing `rave_flutter`:

"Because **`rave_flutter >=0.0.9-alpha+2`** depends on **`flutter_svg ^0.18.1`** and `MY_APP_NAME` depends on **`flutter_svg ^0.19.0`**, **`rave_flutter >=0.0.9-alpha+2`** is forbidden.
So, because `MY_APP_NAME` depends on **`rave_flutter ^0.0.9-alpha+2`**, version solving failed."

Downgrading to  `flutter_svg 0.18.1` worked...but I feel you may want to update `flutter_svg` to the latest version since it's got some bugs fixed. Please do let us know when you do so, we could switch to the latest `flutter_svg` too

Thanks bro. You are doing a good job

**Comment by wilburx9** [comment]
@austyking, please use dependency override to force your project to use `flutter_svg ^0.19.0`.
